services:
  eda-uhdm:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      target: eda-uhdm
    image: localhost/eda-uhdm:local
    working_dir: /workspace
    volumes:
      - .:/workspace

  eda-scc:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
      target: eda-scc
    image: localhost/eda-scc:local
    working_dir: /workspace
    volumes:
      - .:/workspace

  eda-enterprise:
    build:
      context: .
      dockerfile: Dockerfile.rocky8
    image: localhost/eda-enterprise:local
    working_dir: /workspace
    volumes:
      - .:/workspace
